version: '3.4'

services:
  cryptoblade:
    image: cryptoblade:latest
    labels:
        - "autoheal=true"
    ports:
        - 8090:80
    volumes:
        - ./BackTests:/app/BackTests
        - ./HistoricalData:/app/HistoricalData
        - ./OptimizerResults:/app/OptimizerResults
    environment:
        - CB_TradingBot__Accounts__0__ApiKey=
        - CB_TradingBot__Accounts__0__ApiSecret=
        - CB_TradingBot__BotMode=Optimizer
        - CB_TradingBot__StrategyName=Tartaglia
        - CB_TradingBot__BackTest__InitialBalance=5000
        - CB_TradingBot__BackTest__Start=2021-01-01
        - CB_TradingBot__BackTest__End=2023-01-10
        - CB_TradingBot__BackTest__ResultFileName=result.json
        - CB_TradingBot__BackTest__ResultDetailedFileName=result_detailed.json
        - CB_TradingBot__BackTest__DataSource=Binance
        - CB_TradingBot__BackTest__InitialUntradableDays=-2000
        - CB_TradingBot__Optimizer__GeneticAlgorithm__GenerationCount=1000
        - CB_TradingBot__Optimizer__GeneticAlgorithm__MutationProbability=0.01
        - CB_TradingBot__Optimizer__GeneticAlgorithm__CrossoverProbability=0.95
        - CB_TradingBot__Optimizer__GeneticAlgorithm__MinPopulationSize=200
        - CB_TradingBot__Optimizer__GeneticAlgorithm__MaxPopulationSize=250
        - CB_TradingBot__Optimizer__GeneticAlgorithm__FitnessOptions__RunningDaysPreference=0.1
        - CB_TradingBot__Optimizer__GeneticAlgorithm__FitnessOptions__AvgDailyGainPreference=0.7
        - CB_TradingBot__Optimizer__GeneticAlgorithm__FitnessOptions__LowestEquityToBalancePreference=0.2
        - CB_TradingBot__Optimizer__GeneticAlgorithm__FitnessOptions__ExpectedGainsStdDevPreference=0
        - CB_TradingBot__Optimizer__GeneticAlgorithm__FitnessOptions__MaxAvgDailyGainPercent=5
        - CB_TradingBot__Optimizer__GeneticAlgorithm__FitnessOptions__MinAvgDailyGainPercent=-5
        - CB_TradingBot__Optimizer__Tartaglia__ChannelLengthLong__Min=5
        - CB_TradingBot__Optimizer__Tartaglia__ChannelLengthLong__Max=1000
        - CB_TradingBot__Optimizer__Tartaglia__ChannelLengthShort__Min=5
        - CB_TradingBot__Optimizer__Tartaglia__ChannelLengthShort__Max=1000
        - CB_TradingBot__Optimizer__Tartaglia__StandardDeviationLong__Min=0.1
        - CB_TradingBot__Optimizer__Tartaglia__StandardDeviationLong__Max=10
        - CB_TradingBot__Optimizer__Tartaglia__StandardDeviationLong__FractionDigits=1
        - CB_TradingBot__Optimizer__Tartaglia__StandardDeviationShort__Min=0.1
        - CB_TradingBot__Optimizer__Tartaglia__StandardDeviationShort__Max=10
        - CB_TradingBot__Optimizer__Tartaglia__StandardDeviationShort__FractionDigits=1
        - CB_TradingBot__Optimizer__Tartaglia__MinReentryPositionDistanceLong__Min=0.001
        - CB_TradingBot__Optimizer__Tartaglia__MinReentryPositionDistanceLong__Max=0.2
        - CB_TradingBot__Optimizer__Tartaglia__MinReentryPositionDistanceLong__FractionDigits=3
        - CB_TradingBot__Optimizer__Tartaglia__MinReentryPositionDistanceShort__Min=0.001
        - CB_TradingBot__Optimizer__Tartaglia__MinReentryPositionDistanceShort__Max=0.2
        - CB_TradingBot__Optimizer__Tartaglia__MinReentryPositionDistanceShort__FractionDigits=3
        - CB_TradingBot__Optimizer__TradingBot__WalletExposureLong__Min=0
        - CB_TradingBot__Optimizer__TradingBot__WalletExposureLong__Max=3
        - CB_TradingBot__Optimizer__TradingBot__WalletExposureLong__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__WalletExposureShort__Min=0
        - CB_TradingBot__Optimizer__TradingBot__WalletExposureShort__Max=3
        - CB_TradingBot__Optimizer__TradingBot__WalletExposureShort__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__QtyFactorLong__Min=0.001
        - CB_TradingBot__Optimizer__TradingBot__QtyFactorLong__Max=3
        - CB_TradingBot__Optimizer__TradingBot__QtyFactorLong__FractionDigits=3
        - CB_TradingBot__Optimizer__TradingBot__QtyFactorShort__Min=0.001
        - CB_TradingBot__Optimizer__TradingBot__QtyFactorShort__Max=3
        - CB_TradingBot__Optimizer__TradingBot__QtyFactorShort__FractionDigits=3
        - CB_TradingBot__Optimizer__TradingBot__EnableRecursiveQtyFactorLong__Min=false
        - CB_TradingBot__Optimizer__TradingBot__EnableRecursiveQtyFactorLong__Max=true
        - CB_TradingBot__Optimizer__TradingBot__EnableRecursiveQtyFactorShort__Min=false
        - CB_TradingBot__Optimizer__TradingBot__EnableRecursiveQtyFactorShort__Max=true
        - CB_TradingBot__Optimizer__TradingBot__DcaOrdersCount__Min=1
        - CB_TradingBot__Optimizer__TradingBot__DcaOrdersCount__Max=5000
        - CB_TradingBot__Optimizer__TradingBot__UnstuckingEnabled__Min=false
        - CB_TradingBot__Optimizer__TradingBot__UnstuckingEnabled__Max=true
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckThresholdPercent__Min=-1
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckThresholdPercent__Max=-0.01
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckThresholdPercent__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckPositionThresholdPercent__Min=-1
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckPositionThresholdPercent__Max=-0.01
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckPositionThresholdPercent__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckPercentStep__Min=0.01
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckPercentStep__Max=1
        - CB_TradingBot__Optimizer__TradingBot__SlowUnstuckPercentStep__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckThresholdPercent__Min=-1
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckThresholdPercent__Max=-0.01
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckThresholdPercent__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckPositionThresholdPercent__Min=-1
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckPositionThresholdPercent__Max=-0.01
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckPositionThresholdPercent__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckPercentStep__Min=0.01
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckPercentStep__Max=1
        - CB_TradingBot__Optimizer__TradingBot__ForceUnstuckPercentStep__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__ForceKillTheWorst__Min=false
        - CB_TradingBot__Optimizer__TradingBot__ForceKillTheWorst__Max=true
        - CB_TradingBot__Optimizer__TradingBot__MinimumVolume__Min=1000
        - CB_TradingBot__Optimizer__TradingBot__MinimumVolume__Max=30000
        - CB_TradingBot__Optimizer__TradingBot__MinimumPriceDistance__Min=0.015
        - CB_TradingBot__Optimizer__TradingBot__MinimumPriceDistance__Max=0.03
        - CB_TradingBot__Optimizer__TradingBot__MinimumPriceDistance__FractionDigits=3
        - CB_TradingBot__Optimizer__TradingBot__MinProfitRate__Min=0.0006
        - CB_TradingBot__Optimizer__TradingBot__MinProfitRate__Max=0.01
        - CB_TradingBot__Optimizer__TradingBot__MinProfitRate__FractionDigits=4
        - CB_TradingBot__Optimizer__TradingBot__TargetLongExposure__Min=0
        - CB_TradingBot__Optimizer__TradingBot__TargetLongExposure__Max=3
        - CB_TradingBot__Optimizer__TradingBot__TargetLongExposure__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__TargetShortExposure__Min=0
        - CB_TradingBot__Optimizer__TradingBot__TargetShortExposure__Max=3
        - CB_TradingBot__Optimizer__TradingBot__TargetShortExposure__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__MaxLongStrategies__Min=0
        - CB_TradingBot__Optimizer__TradingBot__MaxLongStrategies__Max=15
        - CB_TradingBot__Optimizer__TradingBot__MaxShortStrategies__Min=0
        - CB_TradingBot__Optimizer__TradingBot__MaxShortStrategies__Max=15
        - CB_TradingBot__Optimizer__TradingBot__EnableCriticalModeLong__Min=false
        - CB_TradingBot__Optimizer__TradingBot__EnableCriticalModeLong__Max=true
        - CB_TradingBot__Optimizer__TradingBot__EnableCriticalModeShort__Min=false
        - CB_TradingBot__Optimizer__TradingBot__EnableCriticalModeShort__Max=true
        - CB_TradingBot__Optimizer__TradingBot__CriticalModelWalletExposureThresholdLong__Min=0
        - CB_TradingBot__Optimizer__TradingBot__CriticalModelWalletExposureThresholdLong__Max=3
        - CB_TradingBot__Optimizer__TradingBot__CriticalModelWalletExposureThresholdLong__FractionDigits=2
        - CB_TradingBot__Optimizer__TradingBot__CriticalModelWalletExposureThresholdShort__Min=0
        - CB_TradingBot__Optimizer__TradingBot__CriticalModelWalletExposureThresholdShort__Max=3
        - CB_TradingBot__Optimizer__TradingBot__CriticalModelWalletExposureThresholdShort__FractionDigits=2
        - CB_TradingBot__Optimizer__SessionId=Session01
        - CB_TradingBot__Optimizer__EnableHistoricalDataCaching=true
        - CB_TradingBot__Optimizer__ParallelTasks=10
        - CB_TradingBot__Whitelist__0=ADAUSDT
        - CB_TradingBot__Whitelist__1=ANKRUSDT
        - CB_TradingBot__Whitelist__2=ANTUSDT
        - CB_TradingBot__Whitelist__3=ARKUSDT
        - CB_TradingBot__Whitelist__4=BATUSDT
        - CB_TradingBot__Whitelist__5=BLZUSDT
        - CB_TradingBot__Whitelist__6=BSVUSDT
        - CB_TradingBot__Whitelist__7=CELRUSDT
        - CB_TradingBot__Whitelist__8=CHZUSDT
        - CB_TradingBot__Whitelist__9=COTIUSDT
        - CB_TradingBot__Whitelist__10=CROUSDT
        - CB_TradingBot__Whitelist__11=CVCUSDT
        - CB_TradingBot__Whitelist__12=DENTUSDT
        - CB_TradingBot__Whitelist__13=DGBUSDT
        - CB_TradingBot__Whitelist__14=DOGEUSDT
        - CB_TradingBot__Whitelist__15=DUSKUSDT
        - CB_TradingBot__Whitelist__16=ENJUSDT
        - CB_TradingBot__Whitelist__17=FETUSDT
        - CB_TradingBot__Whitelist__18=FTMUSDT
        - CB_TradingBot__Whitelist__19=GTCUSDT
        - CB_TradingBot__Whitelist__20=HOTUSDT
        - CB_TradingBot__Whitelist__21=ICXUSDT
        - CB_TradingBot__Whitelist__22=IDEXUSDT
        - CB_TradingBot__Whitelist__23=IOSTUSDT
        - CB_TradingBot__Whitelist__24=IOTXUSDT
        - CB_TradingBot__Whitelist__25=KEYUSDT
        - CB_TradingBot__Whitelist__26=KNCUSDT
        - CB_TradingBot__Whitelist__27=LINAUSDT
        - CB_TradingBot__Whitelist__28=LRCUSDT
        - CB_TradingBot__Whitelist__29=MANAUSDT
        - CB_TradingBot__Whitelist__30=MATICUSDT
        - CB_TradingBot__Whitelist__31=MTLUSDT
        - CB_TradingBot__Whitelist__32=NEOUSDT
        - CB_TradingBot__Whitelist__33=NKNUSDT
        - CB_TradingBot__Whitelist__34=OCEANUSDT
        - CB_TradingBot__Whitelist__35=OMGUSDT
        - CB_TradingBot__Whitelist__36=ONEUSDT
        - CB_TradingBot__Whitelist__37=ONTUSDT
        - CB_TradingBot__Whitelist__38=QTUMUSDT
        - CB_TradingBot__Whitelist__39=RENUSDT
        - CB_TradingBot__Whitelist__40=REQUSDT
        - CB_TradingBot__Whitelist__41=RLCUSDT
        - CB_TradingBot__Whitelist__42=RSRUSDT
        - CB_TradingBot__Whitelist__43=RVNUSDT
        - CB_TradingBot__Whitelist__44=SCUSDT
        - CB_TradingBot__Whitelist__45=SNXUSDT
        - CB_TradingBot__Whitelist__46=STORJUSDT
        - CB_TradingBot__Whitelist__47=THETAUSDT
        - CB_TradingBot__Whitelist__48=TOMOUSDT
        - CB_TradingBot__Whitelist__49=TRXUSDT
        - CB_TradingBot__Whitelist__50=VETUSDT
        - CB_TradingBot__Whitelist__51=VGXUSDT
        - CB_TradingBot__Whitelist__52=WAVESUSDT
        - CB_TradingBot__Whitelist__53=XEMUSDT
        - CB_TradingBot__Whitelist__54=XLMUSDT
        - CB_TradingBot__Whitelist__55=XRPUSDT
        - CB_TradingBot__Whitelist__56=XTZUSDT
        - CB_TradingBot__Whitelist__57=XVGUSDT
        - CB_TradingBot__Whitelist__58=ZECUSDT
        - CB_TradingBot__Whitelist__59=ZILUSDT
        - CB_TradingBot__Whitelist__60=ZRXUSDT