version: '3.4'

services:
  cryptoblade:
    image: cryptoblade:latest
    labels:
        - "autoheal=true"
    ports:
        - 8090:80
    volumes:
        - ./BackTests:/app/BackTests
        - ./HistoricalData:/app/HistoricalData
    environment:
        - CB_TradingBot__Accounts__0__ApiKey=
        - CB_TradingBot__Accounts__0__ApiSecret=
        - CB_TradingBot__StrategyName=AutoHedge
        - CB_TradingBot__MaxRunningStrategies=4
        - CB_TradingBot__WalletExposureLong=2.0
        - CB_TradingBot__WalletExposureShort=2.0
        - CB_TradingBot__ForceMinQty=false
        - CB_TradingBot__TradingMode=DynamicBackTest
        - CB_TradingBot__DcaOrdersCount=100
        - CB_TradingBot__DynamicBotCount__TargetLongExposure=2.0
        - CB_TradingBot__DynamicBotCount__TargetShortExposure=2.0
        - CB_TradingBot__DynamicBotCount__MaxLongStrategies=10
        - CB_TradingBot__DynamicBotCount__MaxShortStrategies=10
        - CB_TradingBot__DynamicBotCount__MaxDynamicStrategyOpenPerStep=10
        - CB_TradingBot__DynamicBotCount__Step=0.00:01:00
        - CB_TradingBot__Unstucking__Enabled=true
        - CB_TradingBot__Unstucking__SlowUnstuckThresholdPercent=-0.1
        - CB_TradingBot__Unstucking__SlowUnstuckPositionThresholdPercent=-0.015
        - CB_TradingBot__Unstucking__SlowUnstuckPercentStep=0.10
        - CB_TradingBot__Unstucking__ForceUnstuckThresholdPercent=-0.3
        - CB_TradingBot__Unstucking__ForceUnstuckPositionThresholdPercent=-0.02
        - CB_TradingBot__Unstucking__ForceUnstuckPercentStep=0.01
        - CB_TradingBot__Unstucking__ForceKillTheWorst=true
        - CB_TradingBot__BackTest__InitialBalance=5000
        - CB_TradingBot__BackTest__Start=2023-01-01
        - CB_TradingBot__BackTest__End=2023-08-13
        - CB_TradingBot__BackTest__ResultFileName=result.json
        - CB_TradingBot__BackTest__ResultDetailedFileName=result_detailed.json
        - CB_TradingBot__Whitelist__0=ARBUSDT
        - CB_TradingBot__Whitelist__1=OPUSDT
        - CB_TradingBot__Whitelist__2=XRPUSDT
        - CB_TradingBot__Whitelist__3=LINAUSDT
        - CB_TradingBot__Whitelist__4=TRXUSDT
        - CB_TradingBot__Whitelist__5=NEARUSDT
        - CB_TradingBot__Whitelist__6=SUIUSDT
        - CB_TradingBot__Whitelist__7=GMTUSDT
        - CB_TradingBot__Whitelist__8=ORDIUSDT
        - CB_TradingBot__Whitelist__9=MATICUSDT
        - CB_TradingBot__Whitelist__10=INJUSDT
        - CB_TradingBot__Whitelist__11=ETHWUSDT
        - CB_TradingBot__Whitelist__12=TUSDT
        - CB_TradingBot__Whitelist__13=DOGEUSDT
        - CB_TradingBot__Whitelist__14=SOLUSDT
        - CB_TradingBot__Whitelist__15=BCHUSDT
        - CB_TradingBot__Whitelist__16=LINKUSDT
        - CB_TradingBot__Whitelist__17=GRTUSDT
        - CB_TradingBot__Whitelist__18=MANAUSDT
        - CB_TradingBot__Whitelist__19=1000PEPEUSDT
        - CB_TradingBot__Whitelist__20=STXUSDT
        - CB_TradingBot__Whitelist__21=LDOUSDT
        - CB_TradingBot__Whitelist__22=COMPUSDT
        - CB_TradingBot__Whitelist__23=XLMUSDT
        - CB_TradingBot__Whitelist__24=ETCUSDT
        - CB_TradingBot__Whitelist__25=STORJUSDT
        - CB_TradingBot__Whitelist__26=CELOUSDT
        - CB_TradingBot__Whitelist__27=APTUSDT
        - CB_TradingBot__Whitelist__28=ADAUSDT
        - CB_TradingBot__Whitelist__29=RDNTUSDT
        - CB_TradingBot__Whitelist__30=FLOWUSDT
        - CB_TradingBot__Whitelist__31=AVAXUSDT
        - CB_TradingBot__Whitelist__32=ATOMUSDT
        - CB_TradingBot__Whitelist__33=FILUSDT
        - CB_TradingBot__Whitelist__34=MTLUSDT
        - CB_TradingBot__Whitelist__35=MKRUSDT
        - CB_TradingBot__Whitelist__36=XMRUSDT
        - CB_TradingBot__Whitelist__37=MASKUSDT
        - CB_TradingBot__Whitelist__38=NEOUSDT
        - CB_TradingBot__Whitelist__39=AGLDUSDT
        - CB_TradingBot__Whitelist__40=TRBUSDT
        - CB_TradingBot__Whitelist__41=ZECUSDT
        - CB_TradingBot__Whitelist__42=UNIUSDT
        - CB_TradingBot__Whitelist__43=CVXUSDT
        - CB_TradingBot__Whitelist__44=ZENUSDT
        - CB_TradingBot__Whitelist__45=DYDXUSDT
        - CB_TradingBot__Whitelist__46=AXSUSDT
        - CB_TradingBot__Whitelist__47=GMXUSDT
        - CB_TradingBot__Whitelist__48=OGNUSDT
        - CB_TradingBot__Whitelist__49=ENSUSDT
