version: '3.4'

services:
  cryptoblade:
    image: cryptoblade:latest
    labels:
        - "autoheal=true"
    ports:
        - 8090:80
    volumes:
        - ./BackTests:/app/BackTests
        - ./HistoricalData:/app/HistoricalData
    environment:
        - CB_TradingBot__Accounts__0__ApiKey=
        - CB_TradingBot__Accounts__0__ApiSecret=
        - CB_TradingBot__StrategyName=AutoHedge
        - CB_TradingBot__MaxRunningStrategies=10
        - CB_TradingBot__WalletExposureLong=2.0
        - CB_TradingBot__WalletExposureShort=2.0
        - CB_TradingBot__ForceMinQty=false
        - CB_TradingBot__TradingMode=DynamicBackTest
        - CB_TradingBot__DcaOrdersCount=1000
        - CB_TradingBot__SpotRebalancingRatio=0.5
        - CB_TradingBot__DynamicBotCount__TargetLongExposure=20.0
        - CB_TradingBot__DynamicBotCount__TargetShortExposure=20.0
        - CB_TradingBot__DynamicBotCount__MaxLongStrategies=10
        - CB_TradingBot__DynamicBotCount__MaxShortStrategies=10
        - CB_TradingBot__DynamicBotCount__MaxDynamicStrategyOpenPerStep=10
        - CB_TradingBot__DynamicBotCount__Step=0.00:01:00
        - CB_TradingBot__Unstucking__Enabled=false
        - CB_TradingBot__Unstucking__SlowUnstuckThresholdPercent=-0.1
        - CB_TradingBot__Unstucking__SlowUnstuckPositionThresholdPercent=-10.00
        - CB_TradingBot__Unstucking__SlowUnstuckPercentStep=0.01
        - CB_TradingBot__Unstucking__ForceUnstuckThresholdPercent=-0.5
        - CB_TradingBot__Unstucking__ForceUnstuckPositionThresholdPercent=-0.05
        - CB_TradingBot__Unstucking__ForceUnstuckPercentStep=1.00
        - CB_TradingBot__Unstucking__ForceKillTheWorst=false
        - CB_TradingBot__BackTest__InitialBalance=5000
        - CB_TradingBot__BackTest__Start=2023-01-01
        - CB_TradingBot__BackTest__End=2023-08-17
        - CB_TradingBot__BackTest__ResultFileName=result.json
        - CB_TradingBot__BackTest__ResultDetailedFileName=result_detailed.json
        - CB_TradingBot__Strategies__LinearRegression__ChannelLength=100
        - CB_TradingBot__Strategies__LinearRegression__StandardDeviation=2
        - CB_TradingBot__Whitelist__0=SOLUSDT
        - CB_TradingBot__Whitelist__1=OPUSDT
        - CB_TradingBot__Whitelist__2=SUIUSDT
        - CB_TradingBot__Whitelist__3=DOGEUSDT
        - CB_TradingBot__Whitelist__4=1000PEPEUSDT
        - CB_TradingBot__Whitelist__5=SHIB1000USDT
        - CB_TradingBot__Whitelist__6=XRPUSDT
        - CB_TradingBot__Whitelist__7=DOTUSDT
        - CB_TradingBot__Whitelist__8=APEUSDT
        - CB_TradingBot__Whitelist__9=ARBUSDT